#!/usr/bin/env bash
# script configure ubuntu machine
# install Nginx amd serves a reirection

# update and install nginx
sudo apt-get update -y -qq && \
	sudo apt-get install nginx -y

# starting nginx
sudo service nginx start

# let firewall allow nginx
sudo ufw allow 'Nginx HTTP'

# redirect page
replace_text="server_name _;\n\tlocation /redirect_me{\n\t\treturn 301 \
	http://www.google.com;\n\t}"
sed -i "s/server_name _;/$replace_text/" /etc/nginx/sites-enabled/default

# check nginx stability
sudo nginx -t

# reloading nginx
sudo service nginx reload
