#!/usr/bin/env bash
# script handles SIGTERM, SIGQUIT amd SIGINT signals

pid_file="/var/run/myscript.pid"

function on_sigterm {
	echo "I hate the kill command"
	mop_up
}
function on_sigint {
	echo "Y U no love me?!"
}
function on_sigquit {
	mop_up
}
function mop_up {
	rm -f "$pid_file"
	exit
}
trap 'on_sigterm' SIGTERM
trap 'on_sigint' SIGINT
trap 'on_sigquit' SIGQUIT

echo "$$" > "$pid_file"

while true
do
	echo 'To infinity and beyond'
	sleep 2
done
