#!/usr/bin/env bash
# a script that manages another script using its pid
# turns it to an init script using the single ampasand '&'

script="./manage_my_process"
script_pid="/var/run/my_process.pid"

start() {
	"$script" &
	echo $! > "$script_pid"
	echo "manage_my_process started"
}

stop() {
	pid=$(cat "$script_pid")
	kill "$pid"
	rm -f "$script_pid"
	echo "manage_my_process stopped"
}

restart() {
	stop
	start
	echo "manage_my_process restarted"
}

usage() {
	echo "Usage: manage_my_process {start|stop|restart}"
}

case "$1" in 
	start)
		start
		;;
	stop)
		stop
		;;
	restatt)
		restart
		;;
	*)
		usage
		;;
esac
