#!/usr/bin/env bash
# script stops 4-to_infinity_and_beyond without using kill and killall

script_pid=$(pgrep 4-to_infinity_and_beyond)
if [ -n "$script_pid" ]
then
	pkill "$script_pid"
	echo 'Terminated'
else
	echo 'not found'
fi
