#!/usr/bin/env bash
# script write strory from etc/psswd directory

passwd_file="/etc/passwd"

while IFS=: read -r username pass uid gid info home shell
do
	echo "The User $username is part of the $gid gang," \
		"lives in $home and rides the $shell." \
		"$uid's place is protected by the passcode $pass" \
		"$info, more info about the user here: $info"

done < "$passwd_file"

