#!/usr/bin/env bash
# this script displays the content of the current directory
# but cut the first two digits

for file in *
do
	if [ -f "$file" ] && [[ "$file" != .* ]]; then
		echo "$file" | cut -d'-' -f2
	fi
done
