#!/usr/bin/env bash
# script

# stop nginx
sudo service nginx stop
# set user to run nginx as master process
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
# make it listen on port 8080
sudo sed -i "s/80/8080/" /etc/nginx/site-enabled/default
# change permission to 644
chmod 644 /etc/nginx/nginx.conf
# change ownership
chown nginx:nginx /etc/nginx -R
# check for services running on port 8080 and kill it
for pid in $(pidof apache2)
do
	kill "$pid"
done
