#!/usr/bin/env bash
# script configures nginx to run as nginx user on port 8080
sudo service nginx stop
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sudo sed -i "s/80/8080/" /etc/nginx/site-enabled/default
chmod 644 /etc/nginx/nginx.conf
kill apache2
